name: Build

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
    paths:
      - 'Lemmy.Net.Client/**'
      - .github/workflows/nuget.yml
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Build
        run: dotnet build --configuration Release

      - name: Create config.json
        run: |
          echo '{
            "username": "${{ secrets.TEST_USER }}",
            "password": "${{ secrets.TEST_PASSWORD }}",
            "instanceUrl": "${{ secrets.TEST_INSTANCE }}"
          }' > Lemmy.Net.Tests/config.json
        
      #- name: Test
      #  run: dotnet test        
        
      - name: Pack
        run: dotnet pack Lemmy.Net.Client --configuration Release        
        
      - name: Push
        run: dotnet nuget push Lemmy.Net.Client\bin\Release\Lemmy.Net.Client.*.nupkg  -s https://www.nuget.org/ -k ${{ secrets.NUGET_KEY }}
